// <auto-generated />
using System;
using BugtrackerHF.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BugtrackerHF.Migrations
{
    [DbContext(typeof(BugtrackerHFContext))]
    [Migration("20221206120053_from-scratch")]
    partial class fromscratch
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BugtrackerHF.Models.AdminViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthZeroId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdminViewModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.IssueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentSeverity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("IssueName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserViewModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserViewModelId");

                    b.ToTable("IssueModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.MessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IssueViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserViewModelId")
                        .HasColumnType("int");

                    b.Property<bool>("Viewed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IssueViewModelId");

                    b.HasIndex("UserViewModelId");

                    b.ToTable("MessageModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.NotificationViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("UserViewModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserViewModelId");

                    b.ToTable("NotificationViewModels");
                });

            modelBuilder.Entity("BugtrackerHF.Models.ProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ProjectAdminId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAdminId");

                    b.ToTable("ProjectModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AdminViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("AuthZeroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminViewModelId");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.IssueModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.UserModel", null)
                        .WithMany("IssueList")
                        .HasForeignKey("UserViewModelId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.MessageModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.IssueModel", null)
                        .WithMany("CommentList")
                        .HasForeignKey("IssueViewModelId");

                    b.HasOne("BugtrackerHF.Models.UserModel", null)
                        .WithMany("MessageList")
                        .HasForeignKey("UserViewModelId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.NotificationViewModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.UserModel", null)
                        .WithMany("NotificationList")
                        .HasForeignKey("UserViewModelId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.ProjectModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.AdminViewModel", "ProjectAdmin")
                        .WithMany()
                        .HasForeignKey("ProjectAdminId");

                    b.Navigation("ProjectAdmin");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.AdminViewModel", null)
                        .WithMany("Users")
                        .HasForeignKey("AdminViewModelId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.AdminViewModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BugtrackerHF.Models.IssueModel", b =>
                {
                    b.Navigation("CommentList");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserModel", b =>
                {
                    b.Navigation("IssueList");

                    b.Navigation("MessageList");

                    b.Navigation("NotificationList");
                });
#pragma warning restore 612, 618
        }
    }
}
