// <auto-generated />
using System;
using BugtrackerHF.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BugtrackerHF.Migrations
{
    [DbContext(typeof(BugtrackerHFContext))]
    [Migration("20221214185412_add_sub_user_list")]
    partial class add_sub_user_list
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BugtrackerHF.Models.IssueViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentSeverity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("IssueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserViewModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserViewModelId");

                    b.ToTable("IssueViewModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.MessageViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IssueViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IssueViewModelId");

                    b.ToTable("MessageViewModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.ProjectViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectViewModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthZeroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.Property<int?>("UserViewModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserViewModelId");

                    b.ToTable("UserViewModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.IssueViewModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.UserViewModel", null)
                        .WithMany("IssueList")
                        .HasForeignKey("UserViewModelId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.MessageViewModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.IssueViewModel", null)
                        .WithMany("MessageList")
                        .HasForeignKey("IssueViewModelId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserViewModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.UserViewModel", null)
                        .WithMany("SubUserList")
                        .HasForeignKey("UserViewModelId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.IssueViewModel", b =>
                {
                    b.Navigation("MessageList");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserViewModel", b =>
                {
                    b.Navigation("IssueList");

                    b.Navigation("SubUserList");
                });
#pragma warning restore 612, 618
        }
    }
}
