// <auto-generated />

#nullable disable

using BugtrackerHF.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace BugtrackerHF.Migrations
{
    [DbContext(typeof(BugtrackerHFContext))]
    [Migration("20221208113939_remove_assignedtouserid")]
    partial class remove_assignedtouserid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BugtrackerHF.Models.IssueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentSeverity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("IssueName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserViewModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserViewModelId");

                    b.ToTable("IssueModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.MessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IssueViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Viewed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IssueViewModelId");

                    b.ToTable("MessageModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.ProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthZeroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.IssueModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.UserModel", null)
                        .WithMany("IssueList")
                        .HasForeignKey("UserViewModelId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.MessageModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.IssueModel", null)
                        .WithMany("MessageList")
                        .HasForeignKey("IssueViewModelId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.IssueModel", b =>
                {
                    b.Navigation("MessageList");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserModel", b =>
                {
                    b.Navigation("IssueList");
                });
#pragma warning restore 612, 618
        }
    }
}
