// <auto-generated />

#nullable disable

using BugtrackerHF.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace BugtrackerHF.Migrations
{
    [DbContext(typeof(BugtrackerHFContext))]
    [Migration("20220812162556_Initial_create")]
    partial class Initial_create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BugtrackerHF.Models.IssueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentSeverity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("IssueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserViewModelAuthZeroId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserViewModelAuthZeroId");

                    b.ToTable("IssueModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.MessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IssueViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentMassageId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserViewModelAuthZeroId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Viewed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IssueViewModelId");

                    b.HasIndex("UserViewModelAuthZeroId");

                    b.ToTable("MessageModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.NotificationViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserViewModelAuthZeroId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserViewModelAuthZeroId");

                    b.ToTable("NotificationViewModels");
                });

            modelBuilder.Entity("BugtrackerHF.Models.ProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ProjectAdminAuthZeroId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAdminAuthZeroId");

                    b.ToTable("ProjectModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserModel", b =>
                {
                    b.Property<string>("AuthZeroId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdminViewModelAuthZeroId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthZeroId");

                    b.HasIndex("AdminViewModelAuthZeroId1");

                    b.ToTable("UserModel");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.AdminViewModel", b =>
                {
                    b.HasBaseType("BugtrackerHF.Models.UserModel");

                    b.Property<string>("AdminViewModelAuthZeroId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("AdminViewModelAuthZeroId");

                    b.HasDiscriminator().HasValue("AdminViewModel");
                });

            modelBuilder.Entity("BugtrackerHF.Models.IssueModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.UserModel", null)
                        .WithMany("IssueList")
                        .HasForeignKey("UserViewModelAuthZeroId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.MessageModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.IssueModel", null)
                        .WithMany("CommentList")
                        .HasForeignKey("IssueViewModelId");

                    b.HasOne("BugtrackerHF.Models.UserModel", null)
                        .WithMany("MessageList")
                        .HasForeignKey("UserViewModelAuthZeroId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.NotificationViewModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.UserModel", null)
                        .WithMany("NotificationList")
                        .HasForeignKey("UserViewModelAuthZeroId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.ProjectModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.AdminViewModel", "ProjectAdmin")
                        .WithMany()
                        .HasForeignKey("ProjectAdminAuthZeroId");

                    b.Navigation("ProjectAdmin");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.AdminViewModel", null)
                        .WithMany("Users")
                        .HasForeignKey("AdminViewModelAuthZeroId1");
                });

            modelBuilder.Entity("BugtrackerHF.Models.AdminViewModel", b =>
                {
                    b.HasOne("BugtrackerHF.Models.AdminViewModel", null)
                        .WithMany("Admins")
                        .HasForeignKey("AdminViewModelAuthZeroId");
                });

            modelBuilder.Entity("BugtrackerHF.Models.IssueModel", b =>
                {
                    b.Navigation("CommentList");
                });

            modelBuilder.Entity("BugtrackerHF.Models.UserModel", b =>
                {
                    b.Navigation("IssueList");

                    b.Navigation("MessageList");

                    b.Navigation("NotificationList");
                });

            modelBuilder.Entity("BugtrackerHF.Models.AdminViewModel", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
